export type User = {
	fullname: string;
	workid: string;
	department: string;
	phoneNo: string;
	pcSerialCode: string;
	discCode: string;
};

// Generated by https://quicktype.io

export interface FormInput {
	firstname: string;
	lastname: string;
	workid: string;
	department: string;
	phoneNo: string;
	pcType: string;
	pcSerialCode: string;
	discCode: string;
}
